### ISSUE TITLE
As a User, I want to see a beautiful home page and see useful information on it.

### ISSUE THREAD

**Issue by ModPhoenix** [ModPhoenix/poker-planning#13]

**Comment by thepranaygupta** [comment]
Hi @ModPhoenix. I am interested to work on this, can you please tell me a few ideas for the homepage?

**Comment by ModPhoenix** [comment]
Hey, any improvements and contributions to the home page are welcomed. As you can see it is pretty minimal right now =)

I do not have some specific ideas that I see smart, so I asked chat gpt what can be improved, and here is the answer that I found very good actually at least for start.

Feel free to do what you think would be right, cheers mate

-------------------------

<img width="681" alt="image" src="https://github.com/ModPhoenix/poker-planning/assets/9993443/e979b3ab-abc6-4144-b8fb-750a880912a2">

-------------------------

Improving a website's homepage can encompass several aspects, from visual design and user experience to the technical side of things. Let's go through some possible improvements:

1. **Clear Call to Action (CTA)**: The buttons "Create a room" and "View on Github" are good CTAs, but consider using contrasting colors or more distinctive shapes to make them stand out more.

2. **Visual Hierarchy**: The headline "Planning poker tool for estimating in story points." is quite large and dominates the page, which is good. But you might want to consider the size and positioning of the subtext to ensure it is readable and balances well with the headline.

3. **Navigation**: There does not appear to be any navigation menu. If there are more pages or sections, adding a navigation bar would improve the user experience.

4. **Informational Content**: While the homepage is minimalist, you might want to include a brief explanation or diagram of how planning poker works directly on the homepage, for those who are not familiar with the concept.

5. **Responsive Design**: Ensure that the website is responsive and looks good on all devices. This can't be assessed from the screenshot, but it's important to keep in mind.

6. **Visual Elements**: The dot pattern on the right is a nice, subtle touch that adds some visual interest without being distracting. However, if the page feels too empty, consider adding more graphical elements or illustrations related to agile planning or poker.

7. **About/Contact Information**: Consider adding a section about the team or contact information to make the site more personable and trustworthy.

8. **Loading Speed and SEO**: Make sure that your website is optimized for speed and search engines. This includes optimizing images, minifying CSS and JavaScript, and using proper HTML5 semantic elements.

9. **User Testimonials or Case Studies**: Adding testimonials or case studies can provide social proof and demonstrate the value of your tool.

10. **Footer**: A footer containing legal information, links to social media, a sitemap, or privacy policy could be beneficial for navigation and transparency.

11. **Interactivity**: To make the site more engaging, consider adding interactive elements such as a live demo or interactive tutorial of how the tool works.

12. **Accessibility**: Ensure the website is accessible to all users, including those with disabilities. This includes color contrast for readability and alt text for images.

**Comment by thepranaygupta** [comment]
Thanks for this, I'll share some ideas on this soon.
