### ISSUE TITLE
As a user, I want to see the average score after voting is concluded

### ISSUE THREAD

**Issue by jankratochvilcz** [ModPhoenix/poker-planning#53]
**Is your feature request related to a problem? Please describe.**

When we finish voting, we can't see the average of the cast votes and need to calculate them ourselves, which is imprecise as we just eye-ball the number.

**Describe the solution you'd like**

Show the average after voting is concluded.

**Describe alternatives you've considered**

* Calculate in a spreadsheet on the side
* Eye-ball the average

**Additional context**

If you'd be interested, I'd be willing to take a stab and submit a PR if that'd work. We really enjoy this tool and would love to help with adding extra features as a way to give back!

**Comment by ModPhoenix** [comment]
Thank you for your feature request and for offering to contribute! I agree that displaying the average score after voting concludes would be a valuable addition, so feel free to add this feature.

**Comment by ModPhoenix** [comment]
I am working on app redesign, so I'll take this in work

**Comment by ModPhoenix** [comment]
Here it is

<img width="747" alt="image" src="https://github.com/user-attachments/assets/cc424b6d-90b8-4ff0-8479-672abff7573b">
