### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by minetrinitite** [ModPhoenix/poker-planning#54]
**Describe the bug**
https://www.isitdownrightnow.com/pokerplanning.org.html
Currently the pokerplanning.org website is unavailable.

**To Reproduce**
1. Open a web browser
2. Navigate to url "pokerplanning.org"

**Expected behavior**
Pokerplanning.org website is served.

**Screenshots**
![image](https://github.com/user-attachments/assets/8827e3e5-321b-4ec8-903d-12c741259469)
![image](https://github.com/user-attachments/assets/31e5de7f-d1fe-400b-90b1-6d0354c5ef3d)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 
 - Version: Version 125.0.6422.113 (Official Build) (arm64)

**Additional context**
Any clarity would be appreciated as well.

**Comment by ModPhoenix** [comment]
The issue with pokerplanning.org has been resolved. I have redeployed the app after updating my payment details. The site is now accessible again.
